/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package com.lonebots.testapps.trygroovy

import groovy.xml.XmlParser

class App {

  static void main(String[] args) {
    def rootNode = new XmlParser().parseText(
          '''<?xml version="1.0" encoding="UTF-8"?>
<breakfast_menu>
  <food>
    <name>Belgian Waffles</name>
    <price>$5.95</price>
    <description>Two of our famous Belgian Waffles with plenty of real maple syrup</description>
    <calories>650</calories>
  </food>
  <food>
    <name>Strawberry Belgian Waffles</name>
    <price>$7.95</price>
    <description>Light Belgian waffles covered with strawberries and whipped cream</description>
    <calories>900</calories>
  </food>
  <food>
    <name>Berry-Berry Belgian Waffles</name>
    <price>$8.95</price>
    <description>Light Belgian waffles covered with an assortment of fresh berries and whipped cream</description>
    <calories>900</calories>
  </food>
  <food>
    <name>French Toast</name>
    <price>$4.50</price>
    <description>Thick slices made from our homemade sourdough bread</description>
    <calories>600</calories>
  </food>
  <food>
    <name>Homestyle Breakfast</name>
    <price>$6.95</price>
    <description>Two eggs, bacon or sausage, toast, and our ever-popular hash browns</description>
    <calories>950</calories>
  </food>
  <food>
    <name>Homestyle Breakfast</name>
    <price>$6.95</price>
    <description>Two eggs, bacon or sausage, toast, and our ever-popular hash browns</description>
    <calories>950</calories>
  </food>
</breakfast_menu>
          '''
          )

    def grp = rootNode.children().groupBy {
      item -> item.name[0].value()[0]
    }

    // print grp
    grp.each { key, value ->
      println key + ' ' + value.size() + ' item/s'
      // `inject` is flipping `leftFold/reduce`
      def p = value.price.inject(new BigDecimal('0.00')) { acc, val ->
        new BigDecimal(val[0].value()[0].replaceAll('\\$', '')).add(acc)
      }
      println p
    }
  }

}

/*
NOTES
im still unable to figure what the data type of which
confused about differentiating corresponding types
*/
